### ISSUE TITLE
Nonterminating Evaluation

### ISSUE THREAD

**Issue by isheff** [bogwonch/SecPAL#4]
I seem to be getting an infinite (or at least very, very long) evaluation, which shouldn't happen in SecPAL. A minimal (so far as I can tell) example is:

```
⇒  cat nonterminating.spp
A says A f(x,y) if
  p f(x,y),
  q f(x,y),
  p g(q);

A says P can-say inf P f(x,y);
A says Q can-say inf Q f(x,y);

P says P f(X,Y);
Q says Q f(X,Y);

A says P g(Q);

⇒  cabal run secpal -- -f nonterminating.spp
Preprocessing executable 'secpal' for SecPAL-0.1.0.0...
Running secpal...
Loaded assertion context.
Enter query or :h to see the help
? A says A f(X,Y);
```

**Comment by bogwonch** [comment]
Hi isheff,

My SecPAL implementation is seriously buggy. It was eventually replaced by AppPAL (which is SecPAL with a couple of minor tweaks).  Your example works as expected there:

`
❯ cat nonterminating.spp
'a' says 'a' f(X, Y)
  if P f(X,Y),
     Q f(X,Y),
     P g(Q).

'a' says 'p' can-say inf 'p' f(X,Y).
'a' says 'q' can-say inf 'q' f(X,Y).

'p' says 'p' f('x','y').
'q' says 'q' f('x','y').

'a' says 'p' g('q').

❯ time java -jar AppPAL.jar -i -p nonterminating.spp <<<"'a' says 'a' f('x', 'y')."
AppPAL PPC
 - The App Policy Authorization Logic
   for PC-based Policy Checking

[INFO] loading policy file 'nonterminating.spp'
[INFO] starting REPL
?- YES: 'a' says 'a' f('x', 'y').
'a' says 'a' f('x', 'y') if P f('x', 'y'), Q f('x', 'y'), P g(Q).
  'a' says 'p' f('x', 'y').
    'a' says 'p' can-say inf 'p' f('x', 'y').
    'p' says 'p' f('x', 'y').
  'a' says 'q' f('x', 'y').
    'a' says 'q' can-say inf 'q' f('x', 'y').
    'q' says 'q' f('x', 'y').
  'a' says 'p' g('q').

?-
real	0m0.275s
user	0m0.352s
sys	0m0.057s
`

The repo is available at [https://github.com/bogwonch/libAppPAL](https://github.com/bogwonch/libAppPAL): it's not without it's own problems, but it is fairly serviceable.

I'd be fascinated to here what you're doing with SecPAL and where you came to it from!  I wrote my PhD thesis on analysing mobile device policies with it.  I'm done now, so I have limited time to support it anymore but if you have any question I'll try and help if I have a free moment!

--
Joseph.
